name: Hacktoberfest

on: [issues]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master  # Needed to be able to use in-repo actions
    - uses: ./.github/actions/hacktoberfest
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        label: new contributor
